### ISSUE TITLE
Support f64 values for the `n` parameter

### ISSUE THREAD

**Issue by Bobulous** [ankane/dist-rust#1]
Hello, @ankane.

Do you know of any reason why the algorithm you use could not support type f64 (instead of u32) for the `ppf` function (to calculate the quantile value for the t distribution)?

Reading the linked article "Algorithm 396: Student's t-quantiles" by G W Hill, it suggests that `n` can be taken as a real number (rather than limited to being an integer). So could that be reflected in your `ppf` function (or in an new function called ppf_f64 or something similar) or is there a reason why this Rust code would break if `n` is not an integer value?

If it can be done, could you create a new function to provide this all-arguments-f64 mode? (The only thing I'm wondering about this is whether it would be able to detect that an f64 value is exactly 1.0 or 2.0 in order to return the shortcut calculations. Maybe floating point errors would mean that an f64 can never be exactly 1.0 or 2.0 and so the shortcuts would be impossible. In that case, does the full version of the algorithm still return the correct value for n_f64=1 and n_f64=2, just a bit slower?)

**Comment by ankane** [comment]
Hey @Bobulous, thanks for the suggestion. I updated the existing functions to take a `f64` (as well as an integer). 1 and 2 can be represented exactly in floating point, so there's no issue there.

**Comment by Bobulous** [comment]
Thank you, @ankane.
Are you able to create a new tag/release number so that I can pull your new version (with the f64 parameter type) into Rust projects using Cargo.toml `[dependencies]`?

(And if you like the new gamma function in my pull request, could you give that its own tag/release number too?)
