### ISSUE TITLE
Create new release including recent changes

### ISSUE THREAD

**Issue by Bobulous** [ankane/dist-rust#4]
Hello, @ankane.

Are you able to create a new tag/release number and publish it to crates.io (or wherever the existing release was made available) so that I can pull your new version (with the f64 parameter type) into Rust projects using Cargo.toml [dependencies]?

(And if you like the new gamma function in my [pull request](https://github.com/ankane/dist-rust/pull/3), could you give that its own tag/release number too? If you're not keen on the new gamma function, let me know and I'll bump it into a new repository of its own.)

**Comment by ankane** [comment]
Hey @Bobulous, just pushed 0.1.1 with the f64 change. Still need to review the gamma PR.
